module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      ["feat", "fix", "refactor", "docs", "test", "chore", "build", "ci"],
    ],
    "scope-empty": [2, "never"],
    "scope-enum": [
      2,
      "always",
      [
        "ui",
        "preview",
        "store",
        "media",
        "platform",
        "docs",
        "test",
        "build",
        "deps",
        "electron",
        "gate-checks",
        "gate1",
        "gate2",
        "gate3",
        "gate4",
        "gate5",
        "gate6",
        "gate7",
        "gate8",
        "gate9",
        "gate10",
      ],
    ],
    "subject-empty": [2, "never"],
    "header-max-length": [2, "always", 100],
    "body-max-line-length": [2, "always", 300],
  },
};
