import type { AppState } from './useStore';

export type ProjectSliceContract = Pick<
  AppState,
  | 'setProjectLoaded'
  | 'setProjectPath'
  | 'setVaultPath'
  | 'setTrashPath'
  | 'setProjectName'
  | 'initializeProject'
  | 'clearProject'
  | 'loadProject'
  | 'setRootFolder'
  | 'addSourceFolder'
  | 'removeSourceFolder'
  | 'updateSourceFolder'
  | 'refreshAllSourceFolders'
  | 'toggleFolderExpanded'
  | 'setExpandedFolders'
  | 'addFavorite'
  | 'removeFavorite'
  | 'setSourceViewMode'
  | 'initializeSourcePanel'
  | 'getSourcePanelState'
>;

export type CutTimelineSliceContract = Pick<
  AppState,
  | 'addScene'
  | 'removeScene'
  | 'renameScene'
  | 'reorderScenes'
  | 'updateSceneFolderPath'
  | 'addSceneNote'
  | 'updateSceneNote'
  | 'removeSceneNote'
  | 'addCutToScene'
  | 'addLoadingCutToScene'
  | 'updateCutWithAsset'
  | 'createCutFromImport'
  | 'removeCut'
  | 'updateCutDisplayTime'
  | 'updateCutClipPoints'
  | 'clearCutClipPoints'
  | 'updateCutAsset'
  | 'updateCutLipSync'
  | 'setCutAudioBindings'
  | 'setCutUseEmbeddedAudio'
  | 'reorderCuts'
  | 'moveCutToScene'
  | 'moveCutsToScene'
  | 'setCutRuntime'
  | 'clearCutRuntime'
  | 'getCutRuntime'
  | 'copySelectedCuts'
  | 'pasteCuts'
  | 'canPaste'
>;

export type SelectionUiSliceContract = Pick<
  AppState,
  | 'selectScene'
  | 'selectCut'
  | 'toggleCutSelection'
  | 'selectCutRange'
  | 'selectMultipleCuts'
  | 'clearCutSelection'
  | 'isMultiSelected'
  | 'setPlaybackMode'
  | 'setPreviewMode'
  | 'setCurrentPreviewIndex'
  | 'setGlobalVolume'
  | 'setGlobalMuted'
  | 'toggleGlobalMute'
  | 'openVideoPreview'
  | 'closeVideoPreview'
  | 'openSequencePreview'
  | 'closeSequencePreview'
  | 'setImportingAsset'
  | 'openAssetDrawer'
  | 'closeAssetDrawer'
  | 'toggleAssetDrawer'
  | 'openSidebar'
  | 'closeSidebar'
  | 'toggleSidebar'
  | 'openDetailsPanel'
  | 'closeDetailsPanel'
>;

export type MetadataSliceContract = Pick<
  AppState,
  | 'cacheAsset'
  | 'getAsset'
  | 'loadMetadata'
  | 'saveMetadata'
  | 'attachAudioToCut'
  | 'analyzeAudioAsset'
  | 'detachAudioFromCut'
  | 'getAttachedAudioForCut'
  | 'updateCutAudioOffset'
  | 'setLipSyncForAsset'
  | 'clearLipSyncForAsset'
  | 'removeAssetReferences'
  | 'deleteAssetWithPolicy'
  | 'relinkCutAsset'
>;

export type GroupSliceContract = Pick<
  AppState,
  | 'createGroup'
  | 'deleteGroup'
  | 'toggleGroupCollapsed'
  | 'getCutGroup'
  | 'selectGroup'
  | 'renameGroup'
  | 'addCutsToGroup'
  | 'removeCutFromGroup'
  | 'updateGroupCutOrder'
  | 'getSelectedGroup'
>;
